import Fluent

struct CreateAnyPubTables: AsyncMigration {
    func prepare(on database: Database) async throws {
        try await database.schema(LinkedAccount.schema)
            .id()
            .field("did", .string, .required)
            .field("handle", .string, .required)
            .field("pds_url", .string, .required)
            .field("scope", .string, .required)
            .field("access_token", .string, .required)
            .field("refresh_token", .string, .required)
            .field("linked_at", .datetime, .required)
            .field("updated_at", .datetime, .required)
            .unique(on: "did")
            .create()

        try await database.schema(OAuthStateRecord.schema)
            .id()
            .field("state", .string, .required)
            .field("handle", .string, .required)
            .field("code_verifier", .string, .required)
            .field("redirect_url", .string, .required)
            .field("created_at", .datetime, .required)
            .field("expires_at", .datetime, .required)
            .unique(on: "state")
            .create()

        try await database.schema(PublicationCache.schema)
            .id()
            .field("account_did", .string, .required)
            .field("uri", .string, .required)
            .field("cid", .string)
            .field("name", .string, .required)
            .field("url", .string, .required)
            .field("description", .string)
            .field("theme_type", .string)
            .field("theme_name", .string)
            .field("host", .string)
            .field("synced_at", .datetime, .required)
            .unique(on: "account_did", "uri")
            .create()

        try await database.schema(CoverAsset.schema)
            .id()
            .field("account_did", .string, .required)
            .field("source", .string, .required)
            .field("file_path", .string, .required)
            .field("mime_type", .string, .required)
            .field("byte_size", .int, .required)
            .field("alt_text", .string)
            .field("attribution_json", .string)
            .field("blob_json", .string)
            .field("created_at", .datetime, .required)
            .create()

        try await database.schema(Draft.schema)
            .id()
            .field("account_did", .string, .required)
            .field("publication_uri", .string, .required)
            .field("publication_url", .string, .required)
            .field("title", .string, .required)
            .field("path", .string)
            .field("excerpt", .string)
            .field("tags_json", .string, .required)
            .field("markdown", .string, .required)
            .field("plaintext", .string, .required)
            .field("cover_asset_id", .uuid)
            .field("status", .string, .required)
            .field("scheduled_at", .datetime)
            .field("published_at", .datetime)
            .field("document_uri", .string)
            .field("document_cid", .string)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime, .required)
            .create()

        try await database.schema(PublishAttempt.schema)
            .id()
            .field("draft_id", .uuid, .required)
            .field("status", .string, .required)
            .field("message", .string)
            .field("created_at", .datetime, .required)
            .create()

        try await database.schema(CalendarEventLink.schema)
            .id()
            .field("draft_id", .uuid, .required)
            .field("event_uri", .string, .required)
            .field("event_cid", .string)
            .field("updated_at", .datetime, .required)
            .unique(on: "draft_id")
            .create()

        try await database.schema(SchedulerRun.schema)
            .id()
            .field("started_at", .datetime, .required)
            .field("finished_at", .datetime, .required)
            .field("published_count", .int, .required)
            .field("failed_count", .int, .required)
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema(SchedulerRun.schema).delete()
        try await database.schema(CalendarEventLink.schema).delete()
        try await database.schema(PublishAttempt.schema).delete()
        try await database.schema(Draft.schema).delete()
        try await database.schema(CoverAsset.schema).delete()
        try await database.schema(PublicationCache.schema).delete()
        try await database.schema(OAuthStateRecord.schema).delete()
        try await database.schema(LinkedAccount.schema).delete()
    }
}
